# Creating arrays from lists

In [2]:
import numpy as np

In [3]:
#create - from lists
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype)

print(arr, type(arr), arr.shape) # shape- "Dimentions" , here we have aa 1D list/array which will revert us the shape as "length" of the list


arr2 = np.array([1, 2, 3, 4, 5, "cool", "prime"])
print(arr2, type(arr2), arr2.dtype)
print(arr2, type(arr), arr2.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'cool' 'prime'] <class 'numpy.ndarray'> <U21
['1' '2' '3' '4' '5' 'cool' 'prime'] <class 'numpy.ndarray'> (7,)


In [4]:
# creating 2D array from 2D list
arr2D = np.array([[1, 2, 9], [3, 4, 8], [5, 6, 7], [10, 11, 12]])
print(arr2D, arr2D.shape)

#Shape = "Dimention" (m*n) value i.e rows * column value 
#Imagine a grid with these values (4= [rows],3= [columns]), also our dimension should be a proper holding same sequence of rows and columns

[[ 1  2  9]
 [ 3  4  8]
 [ 5  6  7]
 [10 11 12]] (4, 3)


In [5]:
arr2D = np.array([[1, 2, 9], [3, 4, 8], [5, 6, 7], [10, 11, 12], [13, 15]])
print(arr2D, arr2D.shape)


# here [13, 15] is an inappropriate sequence, the list should have same number of values to get a shape
#setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions.
#The detected shape was (5,) + inhomogeneous part.

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.


# Creating arrays using built-in function

## 1) zeros_like
## --> Return an array of zeros with shape and type of input.

In [6]:
# numpy.zeros(shape, dtype=None (by default it prints it as a float), order='C', *, device=None, like=None)
# Return a new array of given shape and type, filled with zeros.

arr1 = np.zeros((2,3), dtype = "int64") # prefill
print(arr1, arr1.shape)



[[0 0 0]
 [0 0 0]] (2, 3)


## 2) ones
## --> Return a new array setting values to one.


In [7]:

arr2 = np.ones((2,3), dtype = "int64") # prefill
print(arr2, arr2.shape)


# To create a 1D array 
arr3 = np.ones((5,), dtype = "int64") # prefill
print(arr3, arr3.shape)

[[1 1 1]
 [1 1 1]] (2, 3)
[1 1 1 1 1] (5,)




empty
Return a new uninitialized array.


numpy.eye
[source]
Return a 2-D array with ones on the diagonal and zeros elsewhere.

## 3) full
## --> Return a new array of given shape filled with given value.

In [8]:
arr4 = np.full((3,4), 100)  # will fill the given "100" in the given dimention
print(arr4, arr4.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)


## 4) numpy.eye
##  --> Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [13]:
# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
# used for identity matrix = yeh ek square matrix hoti hai, jisme left side diagonal "1" hoti hai baaki poori matrix main "0" fill krti hai 
# --> isme jo value hum pass krte utni ki grid bnti hai (Example- 5 hai toh: 5 rows and 5 column)
arr5 = np.eye(5)
print(arr5, arr5.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] (5, 5)


## 5) numpy.arange
## --> Just like Python's "Range" function  (start, stop, step)

In [15]:
arr6 = np.arange(0, 11, 2)
print(arr6)

[ 0  2  4  6  8 10]


## 6)numpy.linspace
## -->Return evenly spaced numbers over a specified interval

In [19]:
#start se stop tk equally divide krta hai
#Output = “same difference wali series, can say ek AP form krti hai”
# Syntax = numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)


arr7 = np.linspace(1, 100, 3)  # "3" is used to divide the series in 3 equal parts 
print(arr7)

[  1.   50.5 100. ]
