In [2]:
import numpy as np

# Operations on Arrays
## 1) Reshaping

In [3]:
arr = np.array([[1, 2, 9], [3, 4, 8], [5, 6, 7], [10, 11, 12]])
print(arr, arr.shape)



reshaped = arr.reshape((6,2))
print(reshaped, reshaped.shape)


# NOTE : "Reshaping" can only be done when we have compatible numbers
#         Example: here we have total 12 numbers {i.e  in 3 x 4 arrays = 12} so, reshaping should also be in multiple of 12
#                                                                                             {6 x 2} or {3 x 4} or {12 x 1}

[[ 1  2  9]
 [ 3  4  8]
 [ 5  6  7]
 [10 11 12]] (4, 3)
[[ 1  2]
 [ 9  3]
 [ 4  8]
 [ 5  6]
 [ 7 10]
 [11 12]] (6, 2)


## 2) flatten

In [4]:

flattened = arr.flatten()   # --> from 4D to 1D
print(flattened, flattened.shape)

[ 1  2  9  3  4  8  5  6  7 10 11 12] (12,)


## 3) Indexing

In [8]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr[0])          # same as python list indexing

arr = np.array([[1, 2, 9], [3, 4, 8], [5, 6, 7], [10, 11, 12]])
print(arr[0][1])       # defining rows and columns explicitly



[1 2 9]
2


## 4) Fancy indexing

In [10]:

# Fancy indexing :
#                 when we need to access more than 1 element in an array

arr_fancy = np.array([1, 2, 3, 4, 5])
idx = [0, 1, 3]
print(arr[idx])


[[ 1  2  9]
 [ 3  4  8]
 [10 11 12]]


## 5) Boolean indexing

In [17]:
# Based on a particular condition we can filter out our output

arr_boolean = np.array([4, 2, 1, 8, 5])
print(arr_boolean[arr_boolean > 3])      # those with "> 3" got printed
print(arr_boolean[arr_boolean % 2 == 0])  # only evens

[4 8 5]
[4 2 8]


## 6) Slicing

In [21]:
arr_slicing = np.array([4, 2, 1, 8, 5])
                         # similar to python slicing : [start : end : step]
print(arr_slicing[1:4])            
print(arr_slicing[1:])
print(arr_slicing[:4])
print(arr_slicing[::2])  # for alternate elements

[2 1 8]
[2 1 8 5]
[4 2 1 8]
[4 1 5]


In [27]:

nums = [1, 2, 3, 4, 5]
sub_list = nums[1:3]
print(sub_list)
sub_list[0] = 200

print(sub_list)
print(nums)     # will remain same



arr_nums = np.array([1, 2, 3, 4, 5])
sub_arr = arr_nums[1:3]
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr_nums)  # both will reflect changes


[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [28]:
arr_nums = np.array([1, 2, 3, 4, 5])


# BUT TO AVOID CHANGES IN ORIGINAL ARRAY USE ".copy"
sub_arr = arr_nums[1:3].copy()        #---> we are copying the view of the sliced array into this variable, not the entire array
print(sub_arr)

sub_arr[0] = 200

print(sub_arr)
print(arr_nums)


[2 3]
[200   3]
[1 2 3 4 5]
