In [ ]:
# Axes in Multi- Dimensional Array

1D ---> 1 Axis (axis 0)
2D ---> 2 Axes (axis 0 -- ROWS -- VERTICALLY
                axis 1 -- COLUMN -- HORIZONTALLY )

3D ---> 3 Axes  axis 0 -- Depth / Layers
                axis 1 -- Row in each layer
                axis 2 -- Column




   Columns
      |
      C0   C1   C2   C3    
    ---------------------
R0 |  1  |  2  |  3  |  4  |  → Rows
    ---------------------
R1 |  5  |  6  |  7  |  8  |
    ---------------------
R2 |  9  | 10  | 11  | 12 |
    ---------------------




In [2]:
import numpy as np

In [3]:

arr2D = np.array([[1, 2, 9], [3, 4, 8], [5, 6, 7], [10, 11, 12]])
print(arr2D)

print(np.sum(arr2D))

sum_of_columns = np.sum(arr2D, axis = 0)
print(sum_of_columns)         # column wise

sum_of_rows =  np.sum(arr2D, axis = 1)  
print(sum_of_rows)            # row wise


[[ 1  2  9]
 [ 3  4  8]
 [ 5  6  7]
 [10 11 12]]
78
[19 23 36]
[12 15 18 33]


In [5]:
# how to slice in 2D array

print(arr2D[0:2,  1:2])  # column,row

[[2]
 [4]]



## 3D Array

In [6]:
arr3D = np.array([[[1,2], [3, 4], [5,6]], [[7,8], [9, 10], [11, 12]]]) 

print(arr3D, arr3D.shape)

# indexing
print(arr3D[1, 1, 0])

# slicing
print(arr3D[:, 0, :]) # first row from both layers
print(arr3D[:, :, 0]) # first column from both layers

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]


In [7]:
# Manipulating/changing the data 
arr3D[:, 0, :] = 99
print(arr3D)

[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]
