## Vectorization

In [2]:
import numpy as np

In [7]:
# vectorization - it eliminates the use of a operation on individual input and operates in bulk 

arr1 = np.array([1, 2, 3, 5, 6, 7])
arr2 = np.array([10, 12, 13, 15, 16, 17])

print(arr1 ** 2)
print(arr1 + 10)
print(arr1 + arr2)

[ 1  4  9 25 36 49]
[11 12 13 15 16 17]
[11 14 16 20 22 24]


## Broadcasting

In [ ]:
A way to perform operations on arrays of different shapes without manually resizing them.

-----> Instead of copying data, NumPy automatically stretches (broadcasts) the smaller array to match the larger one.


    “If dimensions match or one is 1 → broadcasting works”

In [ ]:
# Scalar + Array

arr = np.array([1, 2, 3]) # Array
result = arr + 5  # Scalar
print(result)

# Output: [6 7 8]

#  5 is broadcast to [5, 5, 5]    --> cause shape of 5 is "1 x 5" and the array is "1 x 3" ==> both have '1', so will be compatible

In [9]:
# Different shapes


arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([10, 20, 30])
print(arr1 + arr2)


[[11 22 33]
 [14 25 36]]


## Normalization

Normalization an array means transforming its value so they fit into a specific scale or range

In [5]:
arr = np.array([[1, 2],[3, 4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr - mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [ ]:
# ab jo humara transformed array hai iska mean '0' aayga and iska standard deviation '1' ke jinte close ho skti hai vo hogi 

In [ ]:
Example -

       (Array)
          |
Index | Value | x - Mean | (x - Mean)^2 |   Z = (x - Mean)/Std
----------------------------------------------------------------
  0   |  10   |   -20    |     400      |       -1.41
  1   |  20   |   -10    |     100      |       -0.71
  2   |  30   |    0     |       0      |        0
  3   |  40   |   +10    |     100      |       +0.71
  4   |  50   |   +20    |     400      |       +1.41
----------------------------------------------------------------
Mean = 30  
Std  ≈ 14.14