1. Aggregation Functions

These functions reduce multiple values into a single value.


In [5]:

import numpy as np

a = np.array([1, 2, 3, 4, 1, 8, 6, 2])



# Aggregation
print(np.sum(a))     # 10
np.prod(a)
np.mean(a)           # 2.5
np.min(a)            # 1
np.max(a)            # 4
np.std(a)          # standard deviation
np.var(a)         # variance
np.median(a)
np.argmin(a)    # gives index of the min value
np.argmax(a)    # gives index of the max value


27


np.int64(5)

In [2]:
# Power

np.power(a, 2)   # a^2 [given desired power, can be 2, 3, etc]
np.sqrt(a)       # square root
np.cbrt(a)       # cube root
np.square(a)      # square



array([ 1,  4,  9, 16])

In [3]:
# Log Functions

np.exp(a)        # e^x
np.log(a)        # natural log
np.log10(a)      # base-10 log
np.log2(a)       # base-2 log

array([0.       , 1.       , 1.5849625, 2.       ])

In [ ]:
# Rounding

x = np.array([1.2, 2.5, 3.7])

np.round(x)   # [1. 2. 4.]
np.floor(x)   # [1. 2. 3.]  round down
np.ceil(x)    # [2. 3. 4.]  upper value
np.trunc(x)   #  to cut the values after decimal


# ~ Difference:

# round → nearest value
# floor → down
# ceil → up

In [6]:
# Extras

print(np.unique(a))
print(np.sort(a))
print(np.abs(a))     # returns absolute value irrespective of +ve or -ve number


[1 2 3 4 6 8]
[1 1 2 2 3 4 6 8]
[1 2 3 4 1 8 6 2]
